steps:                                                                                                                                                                  
  - name: gcr.io/cloud-builders/docker
    id: Build Image
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${BRANCH_NAME}_${SHORT_SHA}"
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push Image
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${BRANCH_NAME}_${SHORT_SHA}"

  - name: gcr.io/cloud-builders/gcloud
    id: Deploy Image
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        # read cloud run service names from substitution variable
        IFS=',' read -r -a cloud_runs <<< "${_SERVICE_NAME}"

        for cr in "${cloud_runs[@]}"
        do

        # deploy cloud run service iteratively
        gcloud run deploy "$cr" --image gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${BRANCH_NAME}_${SHORT_SHA} --region asia-east1

        done

timeout: 1200s

substitutions:
  _CLOUD_RUN_SERVICE_NAMES: "${_SERVICE_NAME}" # default value
